import { productSchema, type Product } from "./schema";

const productSeeds: Product[] = [
  {
    slug: "commerce-starter-nextjs",
    title: "D13S Commerce Starter",
    subtitle: "Source Next.js cho catalog, checkout, account và support ticket.",
    category: "source",
    status: "mock",
    priceVnd: 2490000,
    stack: ["Next.js", "TypeScript", "Supabase", "payOS"],
    useCase: "Ra mắt cửa hàng sản phẩm số có account library.",
    demoUrl: "https://demo.d13s.local/commerce-starter",
    version: "0.9.0-mock",
    updatedAt: "2026-05-18",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, không chuyển nhượng, không bán lại source.",
    mockNotice: "Mock product. Thay bằng source thật trước khi bán production.",
    highlights: [
      "Luồng catalog tới checkout đã chia domain rõ.",
      "Có cấu trúc account library và license entitlement.",
      "Có checklist deploy VPS Docker.",
    ],
    requirements: ["Node.js 24", "Supabase project", "payOS merchant account"],
    deliverables: ["Source code", "Install guide", "Deployment checklist"],
  },
  {
    slug: "saas-dashboard-kit",
    title: "SaaS Dashboard Kit",
    subtitle: "Template dashboard quản trị với bảng dữ liệu, filter và audit surface.",
    category: "template",
    status: "mock",
    priceVnd: 1590000,
    stack: ["Next.js", "Tailwind CSS", "Charts"],
    useCase: "Dựng admin panel hoặc dashboard vận hành cho SaaS nhỏ.",
    demoUrl: "https://demo.d13s.local/saas-dashboard-kit",
    version: "0.8.0-mock",
    updatedAt: "2026-05-16",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, dùng được cho client sau khi mua license riêng.",
    mockNotice: "Mock product. Ảnh, demo và changelog cần thay bằng bản thật.",
    highlights: [
      "Bảng dữ liệu có trạng thái empty, loading và error.",
      "Layout responsive cho admin dày thông tin.",
      "Token màu và typography thống nhất.",
    ],
    requirements: ["Node.js 24", "Next.js App Router"],
    deliverables: ["Template source", "Component guide", "Mock data pack"],
  },
  {
    slug: "plugin-license-gate",
    title: "License Gate Plugin",
    subtitle: "Plugin kiểm tra quyền truy cập file số theo license và thời hạn update.",
    category: "plugin",
    status: "mock",
    priceVnd: 1290000,
    stack: ["TypeScript", "Supabase", "Storage"],
    useCase: "Chặn tải file khi license hết hạn hoặc bị thu hồi.",
    demoUrl: "https://demo.d13s.local/license-gate",
    version: "0.7.0-mock",
    updatedAt: "2026-05-14",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, không dùng cho marketplace bên thứ ba.",
    mockNotice: "Mock product. Cần kiểm thử bảo mật trước khi bán.",
    highlights: [
      "Kiểm tra ownership trước khi sinh signed URL.",
      "Audit log cho mỗi lần tải.",
      "Tách entitlement khỏi payment record.",
    ],
    requirements: ["Supabase Storage private bucket", "Server-side service role"],
    deliverables: ["Plugin module", "RLS checklist", "API examples"],
  },
  {
    slug: "landing-conversion-pack",
    title: "Landing Conversion Pack",
    subtitle: "Bộ section landing page cho sản phẩm số, dịch vụ web và lead form.",
    category: "template",
    status: "mock",
    priceVnd: 890000,
    stack: ["React", "Tailwind CSS", "Lucide"],
    useCase: "Tạo landing page bán source, plugin hoặc dịch vụ nhanh nhưng sạch.",
    demoUrl: "https://demo.d13s.local/landing-pack",
    version: "1.0.0-mock",
    updatedAt: "2026-05-12",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, có thể chỉnh sửa theo thương hiệu riêng.",
    mockNotice: "Mock product. Thay copy và ảnh thật trước launch.",
    highlights: [
      "Hero rõ offer, proof và CTA.",
      "Pricing block, FAQ, comparison table.",
      "Không dùng emoji icon.",
    ],
    requirements: ["React 19", "Tailwind CSS"],
    deliverables: ["Section components", "Copy blocks", "Responsive checklist"],
  },
  {
    slug: "booking-service-template",
    title: "Booking Service Template",
    subtitle: "Template nhận yêu cầu tư vấn thiết kế web và quản lý lead dịch vụ.",
    category: "template",
    status: "mock",
    priceVnd: 1190000,
    stack: ["Next.js", "Server Actions", "Email"],
    useCase: "Thu lead tư vấn website, landing page hoặc customize source.",
    demoUrl: "https://demo.d13s.local/booking-service",
    version: "0.6.0-mock",
    updatedAt: "2026-05-10",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, không bao gồm email provider fee.",
    mockNotice: "Mock product. Provider email chưa cấu hình thật.",
    highlights: [
      "Form có validation, error và success state.",
      "Lead phân loại theo ngân sách và deadline.",
      "Có copy tư vấn dịch vụ rõ phạm vi.",
    ],
    requirements: ["Email provider", "Domain verified"],
    deliverables: ["Template source", "Lead schema", "Service copy map"],
  },
  {
    slug: "content-seo-mdx-kit",
    title: "Content SEO MDX Kit",
    subtitle: "Bộ blog/resource MDX có metadata, canonical và product CTA.",
    category: "source",
    status: "mock",
    priceVnd: 990000,
    stack: ["Next.js", "MDX", "SEO"],
    useCase: "Xây blog kỹ thuật gắn với catalog sản phẩm số.",
    demoUrl: "https://demo.d13s.local/content-seo",
    version: "0.9.0-mock",
    updatedAt: "2026-05-09",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, nội dung mẫu không được dùng như claim thật.",
    mockNotice: "Mock product. Bài viết mẫu phải thay bằng nội dung thật.",
    highlights: [
      "Metadata và internal link nhất quán.",
      "Article layout đọc tốt trên mobile.",
      "Có CTA gắn sản phẩm liên quan.",
    ],
    requirements: ["Next.js App Router", "Content strategy"],
    deliverables: ["Blog routes", "MDX examples", "SEO checklist"],
  },
  {
    slug: "support-ticket-module",
    title: "Support Ticket Module",
    subtitle: "Module ticket cho account, gắn yêu cầu hỗ trợ với order và sản phẩm.",
    category: "plugin",
    status: "mock",
    priceVnd: 1390000,
    stack: ["Supabase", "RLS", "Next.js"],
    useCase: "Quản lý hỗ trợ sau mua có lịch sử rõ ràng.",
    demoUrl: "https://demo.d13s.local/support-ticket",
    version: "0.7.5-mock",
    updatedAt: "2026-05-08",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, không bao gồm SLA vận hành của D13S.",
    mockNotice: "Mock product. Cần thay bằng schema production trước bán.",
    highlights: [
      "Ticket gắn order/product để giảm tranh chấp.",
      "Trạng thái waiting_support và waiting_customer.",
      "Có ownership policy cho khách hàng.",
    ],
    requirements: ["Supabase Auth", "RLS enabled"],
    deliverables: ["Ticket module", "State machine", "RLS examples"],
  },
  {
    slug: "agency-portfolio-system",
    title: "Agency Portfolio System",
    subtitle: "Source portfolio dịch vụ web có case study, gói dịch vụ và proof blocks.",
    category: "source",
    status: "mock",
    priceVnd: 1490000,
    stack: ["Next.js", "Tailwind CSS", "SEO"],
    useCase: "Agency nhỏ cần website bán dịch vụ thiết kế web chuyên nghiệp.",
    demoUrl: "https://demo.d13s.local/agency-portfolio",
    version: "1.0.0-mock",
    updatedAt: "2026-05-06",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, case study mock phải thay bằng dự án thật.",
    mockNotice: "Mock product. Proof và review chưa phải dữ liệu thật.",
    highlights: [
      "Trang services, case studies và contact flow.",
      "Copy tập trung vào chuyển đổi lead.",
      "SEO local service-ready.",
    ],
    requirements: ["Brand assets", "Service package copy"],
    deliverables: ["Source code", "Copy templates", "Launch checklist"],
  },
  {
    slug: "vite-plugin-marketplace",
    title: "Vite Plugin Marketplace Shell",
    subtitle: "Shell UI cho marketplace plugin với grid, compare và install CTA.",
    category: "source",
    status: "mock",
    priceVnd: 1890000,
    stack: ["Vite", "React", "TypeScript"],
    useCase: "Prototype catalog plugin hoặc extension marketplace.",
    demoUrl: "https://demo.d13s.local/plugin-marketplace",
    version: "0.5.0-mock",
    updatedAt: "2026-05-04",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, không bao gồm marketplace vendor logic.",
    mockNotice: "Mock product. Vendor và payout nằm ngoài MVP.",
    highlights: [
      "Catalog plugin có filter và compare.",
      "Chi tiết plugin hiển thị compatibility.",
      "Không bao gồm multi-vendor backend.",
    ],
    requirements: ["Vite", "React 19"],
    deliverables: ["Marketplace shell", "Mock plugin data", "UI states"],
  },
  {
    slug: "nextjs-admin-crm-lite",
    title: "Next.js Admin CRM Lite",
    subtitle: "Source CRM nhẹ cho lead, pipeline, notes và dashboard vận hành.",
    category: "source",
    status: "mock",
    priceVnd: 2190000,
    stack: ["Next.js", "Postgres", "RLS"],
    useCase: "Quản lý lead dịch vụ web và khách mua sản phẩm số.",
    demoUrl: "https://demo.d13s.local/admin-crm-lite",
    version: "0.6.2-mock",
    updatedAt: "2026-05-02",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, không bao gồm tích hợp CRM bên thứ ba.",
    mockNotice: "Mock product. Dữ liệu khách hàng mẫu không phải dữ liệu thật.",
    highlights: [
      "Pipeline lead, notes và activity log.",
      "Dashboard tập trung vận hành.",
      "Chuẩn bị được cho Supabase RLS.",
    ],
    requirements: ["Postgres", "Auth provider"],
    deliverables: ["Admin source", "Schema draft", "Demo data"],
  },
  {
    slug: "digital-delivery-bundle",
    title: "Digital Delivery Bundle",
    subtitle: "Bundle order, entitlement, download và policy surface cho sản phẩm số.",
    category: "bundle",
    status: "mock",
    priceVnd: 3290000,
    stack: ["Next.js", "Supabase", "payOS", "Storage"],
    useCase: "Dựng nền bán file số có kiểm soát quyền tải.",
    demoUrl: "https://demo.d13s.local/digital-delivery",
    version: "0.8.0-mock",
    updatedAt: "2026-05-01",
    supportDays: 30,
    updateMonths: 12,
    license: "1 dự án thương mại, không dùng để bán lại bundle nguyên trạng.",
    mockNotice: "Mock product. Payment provider đang ở chế độ mô phỏng.",
    highlights: [
      "Tách order, payment và entitlement.",
      "Signed URL ngắn hạn cho private storage.",
      "Có flow refund/replacement ở mức policy.",
    ],
    requirements: ["Supabase project", "payOS merchant account", "Private storage bucket"],
    deliverables: ["Commerce modules", "API route examples", "Security checklist"],
  },
  {
    slug: "starter-audit-playbook",
    title: "Starter Audit Playbook",
    subtitle: "Bộ checklist audit source trước khi bán hoặc bàn giao cho khách.",
    category: "template",
    status: "mock",
    priceVnd: 690000,
    stack: ["Docs", "QA", "Security"],
    useCase: "Chuẩn hóa review source, demo, docs, license trước khi publish.",
    demoUrl: "https://demo.d13s.local/audit-playbook",
    version: "1.1.0-mock",
    updatedAt: "2026-04-28",
    supportDays: 30,
    updateMonths: 12,
    license: "1 team nội bộ, không bán lại checklist như sản phẩm riêng.",
    mockNotice: "Mock product. Checklist cần điều chỉnh theo stack thật.",
    highlights: [
      "Code review, UX review, security review.",
      "Proof matrix cho từng sản phẩm.",
      "Session handoff và release gate.",
    ],
    requirements: ["Git workflow", "QA owner"],
    deliverables: ["Audit templates", "Review checklist", "Release gate map"],
  },
];

const parsed = productSeeds.map((product) => productSchema.parse(product));
const slugs = new Set(parsed.map((product) => product.slug));

if (slugs.size !== parsed.length) {
  throw new Error("Product slugs must be unique.");
}

export const products = parsed;
